apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-fayaaz-deployment  # Name specific to dev
  labels:
    app: dev-fayaaz
spec:
  selector:
    matchLabels:
      app: dev-fayaaz
  template:
    metadata:
      labels:
        app: dev-fayaaz
    spec:
      serviceAccountName: dev-fayaaz-app-sa  # Use dev-specific ServiceAccount
      containers:
        - name: dev-fayaaz-container
          image: nginx:latest
