resources:
  - ../../base
  - namespace.yaml

# Include the SCC manifest from the base
configurations:
  - ../../base/scc-add-fayaaz-app-sa.yaml

namespace: dev-namespace  # Set the namespace for this overlay
