resources:
- ../../base
- namespace.yaml
- service.yaml
- route.yaml
- uat-fayaaz-app-sa.yaml
- uat-clusterrole.yaml
- uat-rolebinding.yaml
- scc-add-fayaaz-app-sa.yaml
namespace: uat-fayaaz
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: deployment-patch.yaml
