resources:
  - ../../base
  - namespace.yaml
  - service.yaml
  - route.yaml
  - uat-fayaaz-app-sa.yaml
  - uat-clusterrole.yaml
  - uat-rolebinding.yaml
  - scc-add-fayaaz-app-sa.yaml  # Include the SCC modification for the UAT namespace
patches:
  - path: uat-deployment-patch.yaml
    target:
      kind: Deployment 
      name: uat-fayaaz-deployment
namespace: uat-fayaaz  # Set the namespace for this overlay
