apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uat-fayaaz-app-rolebinding
  namespace: uat-fayaaz  # Placeholder; actual namespace will be set in overlays
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: uat-fayaaz-app-role
subjects:
  - kind: ServiceAccount
    name: uat-fayaaz-app-sa
    namespace: uat-fayaaz  # Placeholder; actual namespace will be set in overlays
