apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fayaaz-app-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "create", "delete"]
