apiVersion: apps/v1
kind: Deployment
metadata:
  name: fayaaz-deployment
  labels:
    app: fayaaz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fayaaz
  template:
    metadata:
      labels:
        app: fayaaz
    spec:
      serviceAccountName: fayaaz-app-sa  # Use the created ServiceAccount
      containers:
      - name: fayaaz-container
        image: nginx:latest  # You can replace this with the actual image for your app
        ports:
        - containerPort: 80
